// src/app/components/field-reservation/field-reservation.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-field-reservation',
  templateUrl: './field-reservation.component.html',
  styleUrl: './field-reservation.component.scss'
})
export class FieldReservationComponent {
  @Input() fieldId: string;
  @Input() fieldName: string;
  @Input() imageSrc: string;

  constructor(private router: Router) {}

  handleReserve() {
    this.router.navigate([`/reservation/${this.fieldId}`])
  }
}

<div class="field-reservation">
    <img src="{{imageSrc}}" alt="{{fieldName}}" class="field-image" />
    <button class="reserve-button" (click)=handleReserve()> Reserve {{fieldName}} </button>
</div>

// src/components/FieldReservation.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

interface FieldReservationProps {
  fieldId: string;
  fieldName: string;
  imageSrc: string;
}

const FieldReservation: React.FC<FieldReservationProps> = ({ fieldId, fieldName, imageSrc }) => {
  const navigate = useNavigate();

  const handleReserve = () => {
    navigate(`/reserve/${fieldId}`);
  };

  return (
    <div className="field-reservation">
      <img src={imageSrc} alt={fieldName} className="field-image" />
      <button onClick={handleReserve}>Reserve {fieldName}</button>
    </div>
  );
};

export default FieldReservation;
