// src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {

  constructor(private router: Router) {}

  handleHomePage() {
    this.router.navigate(['/']);
  }

  handleAdminLogin() {
    this.router.navigate(['/login']);
  }

}

<header class="header">
    <h1><a  href='/' (onclick)=handleHomePage()> Welcome to MD9</a></h1>
    <button class='admin-button' (onclick)=handleAdminLogin()>Admin Zone</button>
  </header>

// src/components/Header.tsx
// // /src/components/Header.tsx
// import React from 'react';
// import { useNavigate } from 'react-router-dom';
// import '../Header.css';

// const Header: React.FC = () => {
//   const navigate = useNavigate();
//   return (
//     <header className="header">
//       <h1>Welcome to MD9</h1>
//       <button onClick={() => navigate('/login')} className="admin-btn">Admin Zone</button>
//     </header>
//   );
// };

// export default Header;
import React from 'react';
import { useNavigate } from 'react-router-dom';

const Header: React.FC = () => {
  const navigate = useNavigate();

  const handleAdminLogin = () => {
    navigate('/admin');
  };

  return (
    <header className="header">
      <h1>Welcome to MD9</h1>
      <button onClick={handleAdminLogin}>Admin Zone</button>
    </header>
  );
};

export default Header;
