// src/app/pages/home-page/home-page.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home-page',
  templateUrl: './home-page.component.html',
  styleUrl: './home-page.component.scss'
})
export class HomePageComponent {
[x: string]: any;

  constructor(private router: Router) {}

  handleCancelReservation() {
    this.router.navigate(['/cancel']);
  }
}

<div class='homepage'>
    <div class="content">
      <button class='cancel-button' (click)=handleCancelReservation()>Cancel Reservation</button>
      <div class="fields-container">
        <app-field-reservation fieldId="1" fieldName="Field 1" imageSrc="../../../../public/images/Field1.jpg" />
        <app-field-reservation fieldId="2" fieldName="Field 2" imageSrc="../../../../public/images/Field2.jpg" />
      </div>
    </div>
  </div>

// src/pages/homePage/HomePage.tsx
import React from 'react';
import FieldReservation from '../../components/fieldReservation/FieldReservation';
import './HomePage.css'
import { useNavigate } from 'react-router-dom';


const navigate = useNavigate();
const handleCancelReservation = () => {
  navigate('/cancel')
}

const HomePage: React.FC = () => {
  return (
    <div className='homepage'>
      <div className="content">
        <button className='cancel-button' onClick={handleCancelReservation}>Cancel Reservation</button>
        <div className="fields-container">
          <FieldReservation fieldId="1" fieldName="Field 1" imageSrc="/images/field1.jpg" />
          <FieldReservation fieldId="2" fieldName="Field 2" imageSrc="/images/field2.jpg" />
        </div>
      </div>
    </div>
  );
};

export default HomePage;
